/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atguigu_ccalljava2_HistoryJNI */

#ifndef _Included_com_atguigu_ccalljava2_HistoryJNI
#define _Included_com_atguigu_ccalljava2_HistoryJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atguigu_ccalljava2_HistoryJNI
 * Method:    saynimei
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_atguigu_ccalljava2_HistoryJNI_saynimei
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
