/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mycalljni_Jniclient */

#ifndef _Included_com_example_mycalljni_Jniclient
#define _Included_com_example_mycalljni_Jniclient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mycalljni_Jniclient
 * Method:    hehe
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_mycalljni_Jniclient_hehe
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
