/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_su_myappconectiontwo_aboutjni_JniClient */

#ifndef _Included_com_example_su_myappconectiontwo_aboutjni_JniClient
#define _Included_com_example_su_myappconectiontwo_aboutjni_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_su_myappconectiontwo_aboutjni_JniClient
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_su_myappconectiontwo_aboutjni_JniClient_callbackAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_example_su_myappconectiontwo_aboutjni_JniClient
 * Method:    callbackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_su_myappconectiontwo_aboutjni_JniClient_callbackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
